### ISSUE TITLE
Question: Is SDS fix included in CM-12.1 ?

### ISSUE THREAD

**Issue by Deepscorn** [ivanmeler/android_device_samsung_n7100#2]
N7100 with
Type: VTU00M
FwRev: 0xf1
are sds-affected which is SuperBrick bug from which I already lost forever one of my 2 N7100 devices. This bug is "fixed" in commit on 9 Jan 2013:
https://github.com/CyanogenMod/android_kernel_samsung_smdk4412/commit/da8461692362317a8ffce4d4646953985fcf4e1d as said in https://wiki.cyanogenmod.org/w/EMMC_Bugs.

So, the question is: which kernel that ROM is using. And does that kernel contain the fix ?

more info: http://forum.xda-developers.com/showthread.php?t=2093599
http://forum.xda-developers.com/galaxy-s3/general/sudden-death-sds-dont-android-4-1-2-cwm-t2091045

**Comment by ivanmeler** [comment]
We are actually using Samsung KitKat based kernel which had fix from samsung so our rom shouldnt cause issues on sds device, I actually have note 2 with insane chip and didnt have issues so far

**Comment by Deepscorn** [comment]
Ok, I see. Tell me please, builds to flash may be taken from here:
http://forum.xda-developers.com/galaxy-note-2/orig-development/cyanogenmod-12-alpha-1-n7100-t2949644
Is it so?

I see there is said that kernel Linux 3.0.x is used. And I found sources http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tag/?h=v3.1-rc1. And it looks to me that there is no such fix. At least, because it is outdated (date of release tag is very old - 2011-08-08). Or your kernel has same version but taken from another source?

**Comment by ivanmeler** [comment]
http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=n7100
GT-N7100_KK_Opensource_Update1.zip

**Comment by Deepscorn** [comment]
Thanks!
